const turns = [
 {q:'What was that hotel I was looking at last night? The one with the rooftop pool overlooking the cathedral.',status:'Searching last night’s activity…',tool:'search_sessions_tool · list_urls_tool',html:'<p>That was <strong>H10 Madison in Barcelona</strong>. You were looking at its rooftop terrace, then comparing rooms with <strong>Hotel Jazz</strong>. Both were still on your shortlist when you stopped.</p>',refs:[['H10 Madison','https://www.h10hotels.com/en/barcelona-hotels/h10-madison/'],['Hotel Jazz','https://www.hoteljazz.com/en/']]},
 {q:'Right. Why was I leaning toward the other one?',status:'Checking your trip notes…',tool:'search_events_tool · recall_memory_tool',html:'<p>Your notes leaned toward <strong>Hotel Jazz</strong> because of its location near Plaça Catalunya. You’d been checking airport transport and liked having fewer things to figure out when you arrived.</p><p>You also wrote: “Madison has the better view, but we’ll probably be out most of the day.”</p>',refs:[['View comparison note','note']]},
 {q:'Oh yeah. What did I still need to check before booking?',status:'Finding where you left off…',tool:'list_sessions_tool · search_events_tool',html:'<p>You’d left two questions in your notes: <strong>can you leave your bags before check-in</strong>, and <strong>does the room rate you selected include free cancellation</strong>?</p><p>You’d opened Hotel Jazz’s booking page, but I couldn’t find a confirmed answer to either in your saved activity.</p>',refs:[['Reopen booking page','https://www.hoteljazz.com/en/']]}
];
const transcript=document.querySelector('#transcript'), typing=document.querySelector('#typing'), composer=document.querySelector('.composer');
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function wait(ms){let left=ms;while(left>0){await delay(50);if(!document.hidden)left-=50;}}
function scroll(){transcript.scrollTo({top:transcript.scrollHeight,behavior:reduced?'instant':'smooth'});}
function renderTurn(n,complete=false){const t=turns[n],div=document.createElement('article');div.className='turn enter';div.innerHTML=`<div class="user">${t.q}</div><div class="agent"><span class="agent-icon" aria-hidden="true">✳</span><div class="answer"><div class="tool ${complete?'':'working'}"><img src="assets/logo.png" alt=""><span>Clippy · ${complete?t.status.replace('…',''):t.status}</span><span class="tool-spinner" aria-hidden="true"></span></div><div class="response">${complete?t.html:''}</div></div></div>`;transcript.append(div);if(complete)addRefs(div,n);scroll();return div;}
function addRefs(div,n){const refs=document.createElement('div');refs.className='refs';for(const [label] of turns[n].refs){const el=document.createElement('span');el.className='ref';el.textContent=label;refs.append(el);}div.querySelector('.response').append(refs);}
async function play(){while(true){transcript.classList.remove('fade-out');transcript.innerHTML='';transcript.scrollTop=0;await wait(900);for(let i=0;i<turns.length;i++){typing.textContent='';composer.classList.add('typing');for(let c=0;c<turns[i].q.length;c+=2){await wait(28);typing.textContent=turns[i].q.slice(0,c+2);}await wait(550);typing.textContent='Reply…';composer.classList.remove('typing');const div=renderTurn(i);await wait(1500);div.querySelector('.tool').classList.remove('working');div.querySelector('.tool span').textContent='Clippy · '+turns[i].status.replace('…','');const response=div.querySelector('.response');const temp=document.createElement('div');temp.innerHTML=turns[i].html;for(const p of [...temp.children]){p.classList.add('enter');response.append(p);scroll();await wait(650);}addRefs(div,i);scroll();await wait(i===2?12000:8500);}transcript.classList.add('fade-out');await wait(650);}}
const mac=document.querySelector('#mac'),options=document.querySelector('#mac-options');function closeMac(){options.hidden=true;mac.setAttribute('aria-expanded','false');}mac.addEventListener('click',()=>{options.hidden=!options.hidden;mac.setAttribute('aria-expanded',String(!options.hidden));});document.addEventListener('click',e=>{if(!e.target.closest('.mac-wrap'))closeMac();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!options.hidden){closeMac();mac.focus();}});
if(!reduced){let scheduled=false;document.addEventListener('pointermove',e=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{document.documentElement.style.setProperty('--dx',`${(e.clientX/innerWidth-.5)*16}px`);document.documentElement.style.setProperty('--dy',`${(e.clientY/innerHeight-.5)*12}px`);scheduled=false;});});play();}else{document.body.classList.add('reduced');for(let i=0;i<turns.length;i++)renderTurn(i,true);typing.textContent='Reply…';}
